### ISSUE TITLE
Faltan Detalles 

### ISSUE THREAD

**Issue by GorreriFranco** [pdep-utn-frd/presentacion-2021-ValentinMartorelli#1]
Valentin,

De que color es la gata y la perra?
En la ultima oración creo que tenes errores de puntuacion y te falta un tilde en la palabra "tambien". Acordate, si es aguda y termina en "n" "s" o vocal, lleva tilde.

No guardare en completa paz hasta que me des mas detalles. - 26:3

Salu2

**Comment by ValentinMartorelli** [comment]
La perra es marroncito tirando cafe con mucha leche, la gata es fade, cambia seguido de color. Ya mismo agrego info
